# -*- coding: utf-8 -*-
"""Rachas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ob3mv3QIKrT0icwqjxRN-HIkNGS5FiPF

# Prueba de la independencia.

Para esta prueba se considera la hipótesis nula:

*   $H_0 :$ Los números de la muestra $ \{ X_i \} $ son independientes.

Luego

*    $H_1 :$ Los números de la muestra $ \{ X_i \} $ no son independientes.
"""

import numpy as np
import math as mt
from scipy.stats import norm

#Lista de numeros pseudoaleatorios
numeros = [
0.78961, 0.05230, 0.10699, 0.55877, 0.14151,
0.76086, 0.12079, 0.27738, 0.65726, 0.79269,
0.80548, 0.82654, 0.29453, 0.20852, 0.42989,
0.58518, 0.98611, 0.34488, 0.34358, 0.11537,
0.89898, 0.57880, 0.67621, 0.05010, 0.00121,
0.28269, 0.73059, 0.70119, 0.18284, 0.49962,
0.38618, 0.76910, 0.68334, 0.55170, 0.10850,
0.79982, 0.45679, 0.21631, 0.87616, 0.55743,
0.58962, 0.33216, 0.03185, 0.61168, 0.09264,
0.69623, 0.17028, 0.05475, 0.91512, 0.76262,
0.29931, 0.30861, 0.83358, 0.51781, 0.03272,
0.57410, 0.26593, 0.85903, 0.43338, 0.35286,
0.24000, 0.65559, 0.38507, 0.90829, 0.94187,
0.93655, 0.88809, 0.81772, 0.36982, 0.19904,
0.54325, 0.62400, 0.09133, 0.41678, 0.33954,
0.58244, 0.85853, 0.88752, 0.33729, 0.15506,
0.23949, 0.53559, 0.33381, 0.49383, 0.75103,
0.19962, 0.65002, 0.74579, 0.79113, 0.63453,
0.19147, 0.40644, 0.08128, 0.73435, 0.22724,
0.22287, 0.07281, 0.64183, 0.44267, 0.72102
]

"""**Determinar la secuencias de 0 y 1, contar el número de rachas pbservadas $C_0$**

Así:

si $x_i \leq x_i-1$ se asigna 0

si $x_i > x_i-1$ se asigna 1



"""

def convertir_rachas(numeros):

  lista = []
  if not numeros:
    return lista
  lista.append(0)
  rachas = 0


  for i in range(1, len(numeros)):
    if numeros[i] > numeros[i-1]:
      lista.append(1)
    else:
      lista.append(0)
    if lista[i] == 1 and lista[i-1] == 0:
      rachas += 1
  return lista, rachas

result_list = convertir_rachas(numeros)
print(result_list)

"""**Calcular valor esperado, varianza y el estadisitico $Z_0$**

Como $C_0$ sigue una distribución normal de media $\mu_{c_0}$ y varianza $σ^2_{c_0}$ y $Z_0$ sigue una distribución normal (0,1). El intervalo de confianza de aceptación es:

$-Z_{α,2} \leq Z_0 \leq Z_{α,2} $
"""

def prueba_de_independencia(rachas, alpha):
  valor_esperado = (2*len(numeros)-1)/3
  varianza = (16*len(numeros)-29)/90
  Z_0 = rachas - valor_esperado / mt.sqrt(varianza)

  z_aplha = norm.ppf(1-alpha/2)

  if Z_0 > z_aplha or Z_0 < -z_aplha:
    print("No se rechaza la hipotesis nula")
  else:
    print("Se rechaza la hipotesis nula")

print("Ingrese nivel de confianza: ")
alpha=float(input())
prueba_de_independencia(result_list[1], alpha)